export const dashboard_container_schema = {
    type: 'dashboard-container',
    category: 'container',
    icon: 'section',
    internal: true,  /* 内部容器组件！！ */
    widgetList: [],
    options: {
        name: '',
        layout: [],
    },
}


export const ext_chart_containers = [
    dashboard_container_schema,
    {
        type: 'section',
        category: 'container',
        icon: 'section',
        widgetList: [],
        options: {
            name: '',
            title: '',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        },
    },

]

export const ext_charts_widgets = [
    {
        type: 'statistic',
        icon: 'statistic',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '今年的增长',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 进度条
    {
        type: 'progressbar',
        icon: 'progressbar',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '进度条',
            showHeader: false,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 柱状图
    {
        type: 'barChart',
        icon: 'barChart',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '柱状图',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 条形图
    {
        type: 'barXChart',
        icon: 'barXChart',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '条形图',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },

    // 折线图
    {
        type: 'lineChart',
        icon: 'lineChart',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '折线图',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 漏斗图
    {
        type: 'funnelChart',
        icon: 'funnelChart',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '漏斗图',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 饼图
    {
        type: 'pieChart',
        icon: 'pieChart',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '饼图',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },

    // 雷达图
    {
        type: 'radarChart',
        icon: 'radarChart',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '雷达图',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 透视表
    {
        type: 'pivotTable',
        icon: 'pivotTable',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '透视表',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
    // 数据列表
    {
        type: 'listTable',
        icon: 'listTable',
        formItemFlag: false,
        options: {
            name: '',
            value: 13232.12,
            title: '数据列表',
            showHeader: true,
            showFullscreen: false,
            showRefresh: false,
            showCollapse: false,
            showIcon: false,
            icon: 'el-icon-star-on',
            iconColor: '#000',
            customClass: [],
            dsEnabled: false,
            dsName: "",
            x: 0,
            y: 0,
            w: 4,
            h: 4,
            onCreated: '',
            onMounted: '',
            onRefresh: '',
        }
    },
]
